language: rust

env:
  global:
    - secure: rKHPhg4mHXV815dEUbUs0cXmRDdaXS16zgMYHbF6TFrZKndczw1s+yG67mUgMz81d/YFfcVl+JjYA0G9DjzNVXx0bNmgmqZ7oyE8XKbbKQ+FYoJK9KU5RMwl8Rbg4eVB6WhPTthwjcyy/9UQh0oHnNJWne0QY2M9IyqufvEG0dU=

script:
  - cargo build
  - cargo test
  - cargo doc

after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh



